#pragma once
#include "GameImages.h"

// Could have found a better way to do this, good start would be using sprite sheets instead of individual images
// for animations.
static constexpr char const* game_image_path[GAME_IMAGE_COUNT] = {
	"resources/MainMenuHeader.png",
	"resources/ButtonBG.png",
	"resources/PopupMenuBG.png",

	"resources/PlayerIdle1.png",
	"resources/PlayerIdle2.png",
	"resources/PlayerIdle3.png",
	"resources/PlayerIdle4.png",
	"resources/PlayerIdle5.png",
	"resources/PlayerIdle6.png",
	"resources/PlayerIdle7.png",

	"resources/PlayerWalk1.png",
	"resources/PlayerWalk2.png",
	"resources/PlayerWalk3.png",
	"resources/PlayerWalk4.png",
	"resources/PlayerWalk5.png",
	"resources/PlayerWalk6.png",
	"resources/PlayerWalk7.png",
	"resources/PlayerWalk8.png",
	"resources/PlayerWalk9.png",

	"resources/PlayerDeath1.png",
	"resources/PlayerDeath2.png",
	"resources/PlayerDeath3.png",
	"resources/PlayerDeath4.png",
	"resources/PlayerDeath5.png",
	"resources/PlayerDeath6.png",
	"resources/PlayerDeath7.png",
	"resources/PlayerDeath8.png",
	"resources/PlayerDeath9.png",
	"resources/PlayerDeath10.png",
	"resources/PlayerDeath11.png",
	"resources/PlayerDeath12.png",
	"resources/PlayerDeath13.png",
	"resources/PlayerDeath14.png",
	"resources/PlayerDeath15.png",
	"resources/PlayerDeath16.png",
	"resources/PlayerDeath17.png",
	"resources/PlayerDeath18.png",

	"resources/SwordsmanWalk1.png",
	"resources/SwordsmanWalk2.png",
	"resources/SwordsmanWalk3.png",
	"resources/SwordsmanWalk4.png",
	"resources/SwordsmanWalk5.png",
	"resources/SwordsmanWalk6.png",
	"resources/SwordsmanWalk7.png",
	"resources/SwordsmanWalk8.png",
	"resources/SwordsmanWalk9.png",
	"resources/SwordsmanWalk10.png",

	"resources/SwordsmanAttack1.png",
	"resources/SwordsmanAttack2.png",
	"resources/SwordsmanAttack3.png",
	"resources/SwordsmanAttack4.png",
	"resources/SwordsmanAttack5.png",
	"resources/SwordsmanAttack6.png",
	"resources/SwordsmanAttack7.png",
	"resources/SwordsmanAttack8.png",

	"resources/SwordsmanDeath1.png",
	"resources/SwordsmanDeath2.png",
	"resources/SwordsmanDeath3.png",
	"resources/SwordsmanDeath4.png",
	"resources/SwordsmanDeath5.png",
	"resources/SwordsmanDeath6.png",
	"resources/SwordsmanDeath7.png",
	"resources/SwordsmanDeath8.png",
	"resources/SwordsmanDeath9.png",
	"resources/SwordsmanDeath10.png",

	"resources/ArcherWalk1.png",
	"resources/ArcherWalk2.png",
	"resources/ArcherWalk3.png",
	"resources/ArcherWalk4.png",
	"resources/ArcherWalk5.png",
	"resources/ArcherWalk6.png",
	"resources/ArcherWalk7.png",
	"resources/ArcherWalk8.png",
	"resources/ArcherWalk9.png",
	"resources/ArcherWalk10.png",

	"resources/ArcherAttack1.png",
	"resources/ArcherAttack2.png",
	"resources/ArcherAttack3.png",
	"resources/ArcherAttack4.png",
	"resources/ArcherAttack5.png",
	"resources/ArcherAttack6.png",
	"resources/ArcherAttack7.png",
	"resources/ArcherAttack8.png",

	"resources/ArcherDeath1.png",
	"resources/ArcherDeath2.png",
	"resources/ArcherDeath3.png",
	"resources/ArcherDeath4.png",
	"resources/ArcherDeath5.png",
	"resources/ArcherDeath6.png",
	"resources/ArcherDeath7.png",
	"resources/ArcherDeath8.png",
	"resources/ArcherDeath9.png",
	"resources/ArcherDeath10.png",
	"resources/ArcherDeath11.png",
	"resources/ArcherDeath12.png",

	"resources/ArcherArrow1.png",
	"resources/ArcherArrow2.png",
	"resources/ArcherArrow3.png",
	"resources/ArcherArrow4.png",

	"resources/TurretIdle1.png",
	"resources/TurretIdle2.png",
	"resources/TurretIdle3.png",

	"resources/TurretAttack1.png",
	"resources/TurretAttack2.png",
	"resources/TurretAttack3.png",
	"resources/TurretAttack4.png",
	"resources/TurretAttack5.png",

	"resources/TurretDeath1.png",
	"resources/TurretDeath2.png",
	"resources/TurretDeath3.png",
	"resources/TurretDeath4.png",
	"resources/TurretDeath5.png",
	"resources/TurretDeath6.png",
	"resources/TurretDeath7.png",
	"resources/TurretDeath8.png",

	"resources/BomberWalk1.png",
	"resources/BomberWalk2.png",
	"resources/BomberWalk3.png",
	"resources/BomberWalk4.png",
	"resources/BomberWalk5.png",
	"resources/BomberWalk6.png",
	"resources/BomberWalk7.png",
	"resources/BomberWalk8.png",
	"resources/BomberWalk9.png",
	"resources/BomberWalk10.png",

	"resources/BomberAttack1.png",
	"resources/BomberAttack2.png",
	"resources/BomberAttack3.png",
	"resources/BomberAttack4.png",
	"resources/BomberAttack5.png",
	"resources/BomberAttack6.png",

	"resources/BomberDeath1.png",
	"resources/BomberDeath2.png",
	"resources/BomberDeath3.png",
	"resources/BomberDeath4.png",
	"resources/BomberDeath5.png",
	"resources/BomberDeath6.png",
	"resources/BomberDeath7.png",
	"resources/BomberDeath8.png",
	"resources/BomberDeath9.png",
	"resources/BomberDeath10.png",
	"resources/BomberDeath11.png",
	"resources/BomberDeath12.png",

	"resources/ItemBorder.png",

	"resources/SwordIcon.png",
	"resources/AOEIcon.png",

	"resources/SwordThrow1.png",
	"resources/SwordThrow2.png",
	"resources/SwordThrow3.png",
	"resources/SwordThrow4.png",
	"resources/SwordThrow5.png",
	"resources/SwordThrow6.png",
	"resources/SwordThrow7.png",
	"resources/SwordThrow8.png",

	"resources/AOEAttack1.png",
	"resources/AOEAttack2.png",
	"resources/AOEAttack3.png",
	"resources/AOEAttack4.png",
	"resources/AOEAttack5.png",
	"resources/AOEAttack6.png",
	"resources/AOEAttack7.png",
	"resources/AOEAttack8.png",
	"resources/AOEAttack9.png",
	"resources/AOEAttack10.png",

	"resources/invalidtile.png",

	"resources/Water1.png",
	"resources/Water2.png",
	"resources/Water3.png",
	"resources/Water4.png",
	"resources/Water5.png",
	"resources/Water6.png",
	"resources/Water7.png",
	"resources/Water8.png",

	"resources/Grass1.png",
	"resources/grassbottomleft.png",
	"resources/grassbottomright.png",
	"resources/grassbottom.png",
	"resources/grasstopright.png",
	"resources/grasstoprightbottomleft.png",
	"resources/grassright.png",
	"resources/grassallbuttopleft.png",
	"resources/grasstopleft.png",
	"resources/grassleft.png",
	"resources/grasstopleftbottomright.png",
	"resources/grassallbuttopright.png",
	"resources/grasstop.png",
	"resources/grassallbutbottomright.png",
	"resources/grassallbutbottomleft.png",

	"resources/Path1.png",
	"resources/pathbottomleft.png",
	"resources/pathbottomright.png",
	"resources/pathbottom.png",
	"resources/pathtopright.png",
	"resources/pathtoprightbottomleft.png",
	"resources/pathright.png",
	"resources/pathallbuttopleft.png",
	"resources/pathtopleft.png",
	"resources/pathleft.png",
	"resources/pathtopleftbottomright.png",
	"resources/pathallbuttopright.png",
	"resources/pathtop.png",
	"resources/pathallbutbottomright.png",
	"resources/pathallbutbottomleft.png",

	"resources/Sand1.png",

	"resources/sandbottomleft1.png",
	"resources/sandbottomleft2.png",
	"resources/sandbottomleft3.png",
	"resources/sandbottomleft4.png",
	"resources/sandbottomleft5.png",
	"resources/sandbottomleft6.png",
	"resources/sandbottomleft7.png",
	"resources/sandbottomleft8.png",
	"resources/sandbottomleft9.png",
	"resources/sandbottomleft10.png",
	"resources/sandbottomleft11.png",
	"resources/sandbottomleft12.png",
	"resources/sandbottomleft13.png",
	"resources/sandbottomleft14.png",
	"resources/sandbottomleft15.png",

	"resources/sandbottomright1.png",
	"resources/sandbottomright2.png",
	"resources/sandbottomright3.png",
	"resources/sandbottomright4.png",
	"resources/sandbottomright5.png",
	"resources/sandbottomright6.png",
	"resources/sandbottomright7.png",
	"resources/sandbottomright8.png",
	"resources/sandbottomright9.png",
	"resources/sandbottomright10.png",
	"resources/sandbottomright11.png",
	"resources/sandbottomright12.png",
	"resources/sandbottomright13.png",
	"resources/sandbottomright14.png",
	"resources/sandbottomright15.png",

	"resources/sandbottom1.png",
	"resources/sandbottom2.png",
	"resources/sandbottom3.png",
	"resources/sandbottom4.png",
	"resources/sandbottom5.png",
	"resources/sandbottom6.png",
	"resources/sandbottom7.png",
	"resources/sandbottom8.png",
	"resources/sandbottom9.png",
	"resources/sandbottom10.png",
	"resources/sandbottom11.png",
	"resources/sandbottom12.png",
	"resources/sandbottom13.png",
	"resources/sandbottom14.png",
	"resources/sandbottom15.png",

	"resources/sandtopright1.png",
	"resources/sandtopright2.png",
	"resources/sandtopright3.png",
	"resources/sandtopright4.png",
	"resources/sandtopright5.png",
	"resources/sandtopright6.png",
	"resources/sandtopright7.png",
	"resources/sandtopright8.png",
	"resources/sandtopright9.png",
	"resources/sandtopright10.png",
	"resources/sandtopright11.png",
	"resources/sandtopright12.png",
	"resources/sandtopright13.png",
	"resources/sandtopright14.png",
	"resources/sandtopright15.png",

	"resources/sandtoprightbottomleft1.png",
	"resources/sandtoprightbottomleft2.png",
	"resources/sandtoprightbottomleft3.png",
	"resources/sandtoprightbottomleft4.png",
	"resources/sandtoprightbottomleft5.png",
	"resources/sandtoprightbottomleft6.png",
	"resources/sandtoprightbottomleft7.png",
	"resources/sandtoprightbottomleft8.png",
	"resources/sandtoprightbottomleft9.png",
	"resources/sandtoprightbottomleft10.png",
	"resources/sandtoprightbottomleft11.png",
	"resources/sandtoprightbottomleft12.png",
	"resources/sandtoprightbottomleft13.png",
	"resources/sandtoprightbottomleft14.png",
	"resources/sandtoprightbottomleft15.png",

	"resources/sandright1.png",
	"resources/sandright2.png",
	"resources/sandright3.png",
	"resources/sandright4.png",
	"resources/sandright5.png",
	"resources/sandright6.png",
	"resources/sandright7.png",
	"resources/sandright8.png",
	"resources/sandright9.png",
	"resources/sandright10.png",
	"resources/sandright11.png",
	"resources/sandright12.png",
	"resources/sandright13.png",
	"resources/sandright14.png",
	"resources/sandright15.png",

	"resources/sandallbuttopleft1.png",
	"resources/sandallbuttopleft2.png",
	"resources/sandallbuttopleft3.png",
	"resources/sandallbuttopleft4.png",
	"resources/sandallbuttopleft5.png",
	"resources/sandallbuttopleft6.png",
	"resources/sandallbuttopleft7.png",
	"resources/sandallbuttopleft8.png",
	"resources/sandallbuttopleft9.png",
	"resources/sandallbuttopleft10.png",
	"resources/sandallbuttopleft11.png",
	"resources/sandallbuttopleft12.png",
	"resources/sandallbuttopleft13.png",
	"resources/sandallbuttopleft14.png",
	"resources/sandallbuttopleft15.png",

	"resources/sandtopleft1.png",
	"resources/sandtopleft2.png",
	"resources/sandtopleft3.png",
	"resources/sandtopleft4.png",
	"resources/sandtopleft5.png",
	"resources/sandtopleft6.png",
	"resources/sandtopleft7.png",
	"resources/sandtopleft8.png",
	"resources/sandtopleft9.png",
	"resources/sandtopleft10.png",
	"resources/sandtopleft11.png",
	"resources/sandtopleft12.png",
	"resources/sandtopleft13.png",
	"resources/sandtopleft14.png",
	"resources/sandtopleft15.png",

	"resources/sandleft1.png",
	"resources/sandleft2.png",
	"resources/sandleft3.png",
	"resources/sandleft4.png",
	"resources/sandleft5.png",
	"resources/sandleft6.png",
	"resources/sandleft7.png",
	"resources/sandleft8.png",
	"resources/sandleft9.png",
	"resources/sandleft10.png",
	"resources/sandleft11.png",
	"resources/sandleft12.png",
	"resources/sandleft13.png",
	"resources/sandleft14.png",
	"resources/sandleft15.png",

	"resources/sandtopleftbottomright1.png",
	"resources/sandtopleftbottomright2.png",
	"resources/sandtopleftbottomright3.png",
	"resources/sandtopleftbottomright4.png",
	"resources/sandtopleftbottomright5.png",
	"resources/sandtopleftbottomright6.png",
	"resources/sandtopleftbottomright7.png",
	"resources/sandtopleftbottomright8.png",
	"resources/sandtopleftbottomright9.png",
	"resources/sandtopleftbottomright10.png",
	"resources/sandtopleftbottomright11.png",
	"resources/sandtopleftbottomright12.png",
	"resources/sandtopleftbottomright13.png",
	"resources/sandtopleftbottomright14.png",
	"resources/sandtopleftbottomright15.png",

	"resources/sandallbuttopright1.png",
	"resources/sandallbuttopright2.png",
	"resources/sandallbuttopright3.png",
	"resources/sandallbuttopright4.png",
	"resources/sandallbuttopright5.png",
	"resources/sandallbuttopright6.png",
	"resources/sandallbuttopright7.png",
	"resources/sandallbuttopright8.png",
	"resources/sandallbuttopright9.png",
	"resources/sandallbuttopright10.png",
	"resources/sandallbuttopright11.png",
	"resources/sandallbuttopright12.png",
	"resources/sandallbuttopright13.png",
	"resources/sandallbuttopright14.png",
	"resources/sandallbuttopright15.png",

	"resources/sandtop1.png",
	"resources/sandtop2.png",
	"resources/sandtop3.png",
	"resources/sandtop4.png",
	"resources/sandtop5.png",
	"resources/sandtop6.png",
	"resources/sandtop7.png",
	"resources/sandtop8.png",
	"resources/sandtop9.png",
	"resources/sandtop10.png",
	"resources/sandtop11.png",
	"resources/sandtop12.png",
	"resources/sandtop13.png",
	"resources/sandtop14.png",
	"resources/sandtop15.png",

	"resources/sandallbutbottomright1.png",
	"resources/sandallbutbottomright2.png",
	"resources/sandallbutbottomright3.png",
	"resources/sandallbutbottomright4.png",
	"resources/sandallbutbottomright5.png",
	"resources/sandallbutbottomright6.png",
	"resources/sandallbutbottomright7.png",
	"resources/sandallbutbottomright8.png",
	"resources/sandallbutbottomright9.png",
	"resources/sandallbutbottomright10.png",
	"resources/sandallbutbottomright11.png",
	"resources/sandallbutbottomright12.png",
	"resources/sandallbutbottomright13.png",
	"resources/sandallbutbottomright14.png",
	"resources/sandallbutbottomright15.png",

	"resources/sandallbutbottomleft1.png",
	"resources/sandallbutbottomleft2.png",
	"resources/sandallbutbottomleft3.png",
	"resources/sandallbutbottomleft4.png",
	"resources/sandallbutbottomleft5.png",
	"resources/sandallbutbottomleft6.png",
	"resources/sandallbutbottomleft7.png",
	"resources/sandallbutbottomleft8.png",
	"resources/sandallbutbottomleft9.png",
	"resources/sandallbutbottomleft10.png",
	"resources/sandallbutbottomleft11.png",
	"resources/sandallbutbottomleft12.png",
	"resources/sandallbutbottomleft13.png",
	"resources/sandallbutbottomleft14.png",
	"resources/sandallbutbottomleft15.png",

	"resources/PowerUp1.png",
	"resources/PowerUp2.png",
	"resources/PowerUp3.png",
	"resources/PowerUp4.png",
	"resources/PowerUp5.png",
	"resources/PowerUp6.png",
	"resources/PowerUp7.png",
	"resources/PowerUp8.png",

	"resources/MonoFont32pt.png",
	"resources/MonoFont16pt.png",
};